# MPLAB IDE generated this makefile for use with GNU make.
# Project: i2c.mcp
# Date: Sun Jul 03 01:28:10 2016

AS = MPASMWIN.exe
CC = mcc18.exe
LD = mplink.exe
AR = mplib.exe
RM = rm

i2c.cof : Untitled.o
	$(LD) /p18F4520 /l"C:\MCC18\lib" /k"C:\MCC18\bin\LKR" "Untitled.o" /u_CRUNTIME /u_DEBUG /z__MPLAB_BUILD=1 /z__MPLAB_DEBUG=1 /o"i2c.cof" /M"i2c.map" /W

Untitled.o : Untitled.c ../../../../MCC18/h/p18f4520.h
	$(CC) -p=18F4520 /i"C:\MCC18\h" "Untitled.c" -fo="Untitled.o" -D__DEBUG -Ou- -Ot- -Ob- -Op- -Or- -Od- -Opa-

clean : 
	$(RM) "Untitled.o" "i2c.cof" "i2c.hex"

